language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
script:
  - npm run fetch-release
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
